name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: Build version
        default: ''
        required: false
        type: string
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  DOTNET_VERSION: 6.0.x
  BUILD_VERSION: ${{ inputs.version || github.ref_name }}
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: |
          ./build.sh "${BUILD_VERSION}"
      - uses: actions/upload-artifact@v4
        with:
          path: '${{ github.workspace }}/build/*.tar.gz'
