name: Build
on:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  DOTNET_VERSION: 8.0.x
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: |
          COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-9)
          BUILD_VERSION="${GITHUB_REF_NAME}-${COMMIT_HASH}"

          ./build.sh "${BUILD_VERSION}"
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/*.tar.gz
            ${{ github.workspace }}/build/*.zip
