name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  DOTNET_VERSION: 8.0.x
  DATABASE_HOST: 127.0.0.1
  DATABASE_USER: sa
  DATABASE_PASSWORD: 8rLCbRdR
jobs:
  test:
    runs-on: ubuntu-24.04
    services:
      # https://hub.docker.com/_/microsoft-mssql-server
      # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#configuring-the-runner-job-for-jobs-directly-on-the-runner-machine
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: y
          MSSQL_SA_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          MSSQL_PID: Express
        ports:
          - 1433:1433
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Run tests
        run: |
          dotnet run --project tests/
